const releasesConstants = {
  SET_RELEASES: 'SET_RELEASES',
  SET_LOADING_RELEASES: 'SET_LOADING_RELEASES',
  SET_ERROR_RELEASES: 'SET_ERROR_RELEASES',
  PAGE_SIZE: 10,
  SET_SPLITS: 'SET_SPLITS',
  SET_ERROR_SPLITS: 'SET_ERROR_SPLITS',
  SET_LOADING_SPLITS: 'SET_LOADING_SPLITS'
};

export default releasesConstants;
