
const subcategoriesConstants = {
  SET_LOADING_SUBCATEGORIES: "SET_LOADING_SUBCATEGORIES",
  SET_SUBCATEGORIES: "SET_SUBCATEGORIES",
  SET_CREATING_SUBCATEGORY: "SET_CREATING_SUBCATEGORY",
  SET_CREATED_SUBCATEGORY: "SET_CREATED_SUBCATEGORY",
  SET_DELETING_SUBCATEGORIES: "SET_DELETING_SUBCATEGORIES",
  REMOVE_SUBCATEGORY: "REMOVE_SUBCATEGORY",
  SET_EDITING_SUBCATEGORIES: "SET_EDITING_CATEGORIES",
  SET_EDITED_SUBCATEGORIES: "SET_EDITED_CATEGORIES",
};

export default subcategoriesConstants;
