const applicationsConstants = {
    SET_LOADING_APPLICATIONS:'SET_LOADING_APPLICATIONS',
    SET_APPLICATIONS: 'SET_APPLICATIONS',
    SET_SEND_CONTRACT_LOADING: 'SET_SEND_CONTRACT_LOADING',
}

export default applicationsConstants