const purchasesConstants = {
  SET_LOADING_PURCHASES: 'SET_LOADING_PURCHASES',
  SET_PURCHASES: 'SET_PURCHASES',
  SET_EDIT_PURCHASE_ERROR: 'SET_EDIT_PURCHASE_ERROR',
  SET_EDITED_PURCHASE: 'SET_EDITED_PURCHASE',
  SET_LOADING_EDIT_PURCHASES: 'SET_LOADING_EDIT_PURCHASES',
  SET_SELECTED_PURCHASES: 'SET_SELECTED_PURCHASES',
};

export default purchasesConstants;
