
const userConstants = {
  SET_USER: 'SET_USER',

  CHECKING_SESSION: 'USER_CHECKING_SESSION',
  CHEKED_SESSION: 'CHEKED_SESSION',
  
  LOGGING_IN: 'USER_LOGGING_IN',
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',

  LOGGING_OUT: 'USER_LOGGING_OUT',

  FETCHING_USER: 'FETCHING_USER',
  FETCH_USER_ERROR: 'FETCH_USER_ERROR',
  SET_USER_INFO: 'SET_USER_INFO',
};

export default userConstants;