const usersConstants = {
  SET_LABEL: 'SET_LABEL',
  SET_LOADING_USERS: 'SET_LOADING_USERS',
  SET_USERS: 'SET_USERS',
  CHECKING_HOME: 'CHECKING_HOME',
  SET_HOME: 'SET_HOME',
  SET_EDITING_USER: 'SET_EDITING_USER',
  SET_EDIT_ERROR: 'SET_EDIT_ERROR',
  SET_EDIT_OK: 'SET_EDIT_OK',
  SET_LOADING_LABEL: 'SET_LOADING_LABEL',
  SET_LABEL_ERROR: 'SET_LABEL_ERROR',
  PAGE_SIZE: 10,
};

export default usersConstants;
